# Rename from pretty names to original ones

In [ ]:
project_name = "{{ project_name }}"

In [ ]:
from pyprojroot import here
crowns_path = here(f"{project_name}_crowns.gpkg")
grid_path = here(f"{project_name}_grid.gpkg")
dir_cor_pretty = here("Corrected_pretty_names")
dir_cor = here("Corrected_pcs")
dir_sel = here("Propagation/selected_trees")

## Make map

an old tree name is made of a `<project-prefix>_<cell-id>_<tree-id>` and gets mapped to a pretty name of `<pretty-cell-name>_<tree-id>` for example:

```
'Lama_02_seg.laz' --> 'FIS01-02_345910_8059490_02_seg.laz'
```

since there are new trees we need to reconstruct this mapping.

The first step is to load the grid mapping

In [ ]:
import geopandas as gpd
from fastcore.xtras import *
from pathlib import Path

In [ ]:
grid = gpd.read_file(grid_path)
grid.head(5)

,cell_id,grid_x,grid_y,pretty_name,geometry
0,345910_8059490,345910,8059490,Lama,"POLYGON ((345920 8059490, 345920 8059500, 3459..."
1,345910_8059500,345910,8059500,Mada,"POLYGON ((345920 8059500, 345920 8059510, 3459..."
2,345910_8059510,345910,8059510,Obus,"POLYGON ((345920 8059510, 345920 8059520, 3459..."
3,345920_8059480,345920,8059480,Aata,"POLYGON ((345930 8059480, 345930 8059490, 3459..."
4,345920_8059490,345920,8059490,Kali,"POLYGON ((345930 8059490, 345930 8059500, 3459..."

get the prefix from the crowns file (that has the mapping for the existing trees)

In [ ]:
crowns = gpd.read_file(crowns_path)

In [ ]:
crowns.head(5)

,GIS_ID,ID_number,area,area.1,cell_id,grid_x,grid_y,grid_x_norm,grid_y_norm,hilbert_dist,suffix,pretty_name,segmented,notes,is_dead,is_removed,is_new,geometry
0,FIS01-02_345910_8059490_02,345910_8059490_02,3.651367,3.651367,345910_8059490,345910.0,8059490.0,0.0,20.0,944.0,02,Lama_02,True,None,False,NaN,NaN,"POLYGON ((345910.853 8059491.292, 345910.858 8..."
1,FIS01-02_345910_8059490_05,345910_8059490_05,16.017580,16.017580,345910_8059490,345910.0,8059490.0,0.0,20.0,944.0,05,Lama_05,True,None,False,NaN,NaN,"POLYGON ((345908.036 8059493.668, 345908.036 8..."
2,FIS01-02_345910_8059490_06,345910_8059490_06,4.727412,4.727412,345910_8059490,345910.0,8059490.0,0.0,20.0,944.0,06,Lama_06,True,None,False,NaN,NaN,"POLYGON ((345912.998 8059497.032, 345913.008 8..."
3,FIS01-02_345910_8059490_07,345910_8059490_07,10.067097,10.067097,345910_8059490,345910.0,8059490.0,0.0,20.0,944.0,07,Lama_07,True,None,False,NaN,NaN,"POLYGON ((345913.142 8059489.798, 345913.19 80..."
4,FIS01-02_345910_8059490_09,345910_8059490_09,3.543199,3.543199,345910_8059490,345910.0,8059490.0,0.0,20.0,944.0,09,Lama_09,True,None,False,NaN,NaN,"POLYGON ((345914.558 8059495.864, 345914.568 8..."

In [ ]:
prefix = crowns['GIS_ID'][0].split("_")[0]
prefix

'FIS01-02'

In [ ]:
grid_pretty2old = {
    row.pretty_name: f"{prefix}_{row.cell_id}"
    for _, row in grid.iterrows()
}
grid_pretty2old

{'Lama': 'FIS01-02_345910_8059490',
 'Mada': 'FIS01-02_345910_8059500',
 'Obus': 'FIS01-02_345910_8059510',
 'Aata': 'FIS01-02_345920_8059480',
 'Kali': 'FIS01-02_345920_8059490',
 'Jaya': 'FIS01-02_345920_8059500',
 'Naia': 'FIS01-02_345920_8059510',
 'Odax': 'FIS01-02_345920_8059520',
 'Bako': 'FIS01-02_345930_8059470',
 'Ecto': 'FIS01-02_345930_8059480',
 'Faba': 'FIS01-02_345930_8059490',
 'Iago': 'FIS01-02_345930_8059500',
 'Psoa': 'FIS01-02_345930_8059510',
 'Okea': 'FIS01-02_345930_8059520',
 'Omus': 'FIS01-02_345930_8059530',
 'Zuma': 'FIS01-02_345930_8059540',
 'Ceto': 'FIS01-02_345940_8059470',
 'Daku': 'FIS01-02_345940_8059480',
 'Gaga': 'FIS01-02_345940_8059490',
 'Hada': 'FIS01-02_345940_8059500',
 'Paha': 'FIS01-02_345940_8059510',
 'Oxya': 'FIS01-02_345940_8059520',
 'Owra': 'FIS01-02_345940_8059530',
 'Zora': 'FIS01-02_345940_8059540',
 'Zeus': 'FIS01-02_345940_8059550',
 'Zaus': 'FIS01-02_345940_8059560',
 'Ugni': 'FIS01-02_345950_8059490',
 'Ucla': 'FIS01-02_345950_8059500',
 'Ptyx': 'FIS01-02_345950_8059510',
 'Saba': 'FIS01-02_345950_8059520',
 'Raja': 'FIS01-02_345950_8059530',
 'Weda': 'FIS01-02_345950_8059540',
 'Xana': 'FIS01-02_345950_8059550',
 'Yoda': 'FIS01-02_345950_8059560',
 'Ubis': 'FIS01-02_345960_8059500',
 'Uaru': 'FIS01-02_345960_8059510',
 'Spio': 'FIS01-02_345960_8059520',
 'Taia': 'FIS01-02_345960_8059530',
 'Vini': 'FIS01-02_345960_8059540',
 'Urva': 'FIS01-02_345960_8059550',
 'Unio': 'FIS01-02_345960_8059560',
 'Thor': 'FIS01-02_345970_8059530',
 'Vaga': 'FIS01-02_345970_8059540',
 'Uvik': 'FIS01-02_345970_8059550',
 'Ulva': 'FIS01-02_345980_8059550'}

In [ ]:
def get_old_name(pretty_tree: str):
    cell_name = pretty_tree.split("_")[0]
    new_name = pretty_tree.replace(cell_name, grid_pretty2old[cell_name])
    return new_name

In [ ]:
get_old_name("Aata_02_seg.laz")

'FIS01-02_345920_8059480_02_seg.laz'

In [ ]:
pretty2old = {
    pretty_tree: get_old_name(pretty_tree.name) for pretty_tree in dir_cor_pretty.ls()
}
pretty2old

{Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Aata_02_seg.laz'): 'FIS01-02_345920_8059480_02_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Aata_05_seg.laz'): 'FIS01-02_345920_8059480_05_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Aata_08_seg.laz'): 'FIS01-02_345920_8059480_08_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Aata_14_seg.laz'): 'FIS01-02_345920_8059480_14_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Aata_15_seg.laz'): 'FIS01-02_345920_8059480_15_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Aata_16_seg.laz'): 'FIS01-02_345920_8059480_16_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Aata_17_seg.laz'): 'FIS01-02_345920_8059480_17_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Bako_12_seg.laz'): 'FIS01-02_345930_8059470_12_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Bako_15_seg.laz'): 'FIS01-02_345930_8059470_15_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Bako_25_seg.laz'): 'FIS01-02_345930_8059470_25_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Ceto_06_seg.laz'): 'FIS01-02_345940_8059470_06_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Ceto_14_seg.laz'): 'FIS01-02_345940_8059470_14_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Ceto_19_seg.laz'): 'FIS01-02_345940_8059470_19_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Daku_01_seg.laz'): 'FIS01-02_345940_8059480_01_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Daku_08_seg.laz'): 'FIS01-02_345940_8059480_08_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Daku_09_seg.laz'): 'FIS01-02_345940_8059480_09_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Daku_10_seg.laz'): 'FIS01-02_345940_8059480_10_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Daku_11_seg.laz'): 'FIS01-02_345940_8059480_11_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Daku_12_seg.laz'): 'FIS01-02_345940_8059480_12_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Daku_13_seg.laz'): 'FIS01-02_345940_8059480_13_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Daku_23_seg.laz'): 'FIS01-02_345940_8059480_23_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Daku_24_seg.laz'): 'FIS01-02_345940_8059480_24_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Daku_32p_seg.laz'): 'FIS01-02_345940_8059480_32p_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Daku_33_seg.laz'): 'FIS01-02_345940_8059480_33_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Daku_34_seg.laz'): 'FIS01-02_345940_8059480_34_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Ecto_00_seg.laz'): 'FIS01-02_345930_8059480_00_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Ecto_02_seg.laz'): 'FIS01-02_345930_8059480_02_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Ecto_03_seg.laz'): 'FIS01-02_345930_8059480_03_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Ecto_05_seg.laz'): 'FIS01-02_345930_8059480_05_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Ecto_06_seg.laz'): 'FIS01-02_345930_8059480_06_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Ecto_08_seg.laz'): 'FIS01-02_345930_8059480_08_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Ecto_09_seg.laz'): 'FIS01-02_345930_8059480_09_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Ecto_12_seg.laz'): 'FIS01-02_345930_8059480_12_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Ecto_13_seg.laz'): 'FIS01-02_345930_8059480_13_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Ecto_21_seg.laz'): 'FIS01-02_345930_8059480_21_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_00b_seg.laz'): 'FIS01-02_345930_8059490_00b_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_01_seg.laz'): 'FIS01-02_345930_8059490_01_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_02_seg.laz'): 'FIS01-02_345930_8059490_02_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_04_seg.laz'): 'FIS01-02_345930_8059490_04_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_05_seg.laz'): 'FIS01-02_345930_8059490_05_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_06_seg.laz'): 'FIS01-02_345930_8059490_06_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_10_seg.laz'): 'FIS01-02_345930_8059490_10_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_11_seg.laz'): 'FIS01-02_345930_8059490_11_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_12_seg.laz'): 'FIS01-02_345930_8059490_12_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_13_seg.laz'): 'FIS01-02_345930_8059490_13_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_14_seg.laz'): 'FIS01-02_345930_8059490_14_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_17_seg.laz'): 'FIS01-02_345930_8059490_17_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_21_seg.laz'): 'FIS01-02_345930_8059490_21_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_26_seg.laz'): 'FIS01-02_345930_8059490_26_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_29p_seg.laz'): 'FIS01-02_345930_8059490_29p_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_30p_seg.laz'): 'FIS01-02_345930_8059490_30p_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_31_seg.laz'): 'FIS01-02_345930_8059490_31_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Gaga_02_seg.laz'): 'FIS01-02_345940_8059490_02_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Gaga_04_seg.laz'): 'FIS01-02_345940_8059490_04_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Gaga_09_seg.laz'): 'FIS01-02_345940_8059490_09_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Gaga_16_seg.laz'): 'FIS01-02_345940_8059490_16_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Gaga_31_seg.laz'): 'FIS01-02_345940_8059490_31_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Gaga_34_seg.laz'): 'FIS01-02_345940_8059490_34_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Hada_02_seg.laz'): 'FIS01-02_345940_8059500_02_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Hada_03_seg.laz'): 'FIS01-02_345940_8059500_03_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Hada_10_seg.laz'): 'FIS01-02_345940_8059500_10_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Hada_13_seg.laz'): 'FIS01-02_345940_8059500_13_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Hada_16_seg.laz'): 'FIS01-02_345940_8059500_16_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Hada_17_seg.laz'): 'FIS01-02_345940_8059500_17_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Hada_18_seg.laz'): 'FIS01-02_345940_8059500_18_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Hada_28_seg.laz'): 'FIS01-02_345940_8059500_28_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Hada_37_seg.laz'): 'FIS01-02_345940_8059500_37_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_00_seg.laz'): 'FIS01-02_345930_8059500_00_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_01_seg.laz'): 'FIS01-02_345930_8059500_01_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_03_seg.laz'): 'FIS01-02_345930_8059500_03_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_04_seg.laz'): 'FIS01-02_345930_8059500_04_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_06_seg.laz'): 'FIS01-02_345930_8059500_06_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_07_seg.laz'): 'FIS01-02_345930_8059500_07_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_08_seg.laz'): 'FIS01-02_345930_8059500_08_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_09_seg.laz'): 'FIS01-02_345930_8059500_09_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_13_seg.laz'): 'FIS01-02_345930_8059500_13_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_15_seg.laz'): 'FIS01-02_345930_8059500_15_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_16_seg.laz'): 'FIS01-02_345930_8059500_16_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_19_seg.laz'): 'FIS01-02_345930_8059500_19_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_21_seg.laz'): 'FIS01-02_345930_8059500_21_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_26b_seg.laz'): 'FIS01-02_345930_8059500_26b_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_35_seg.laz'): 'FIS01-02_345930_8059500_35_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_41_seg.laz'): 'FIS01-02_345930_8059500_41_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_00_seg.laz'): 'FIS01-02_345920_8059500_00_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_02_seg.laz'): 'FIS01-02_345920_8059500_02_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_04_seg.laz'): 'FIS01-02_345920_8059500_04_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_05_seg.laz'): 'FIS01-02_345920_8059500_05_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_06_seg.laz'): 'FIS01-02_345920_8059500_06_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_20_seg.laz'): 'FIS01-02_345920_8059500_20_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_25_seg.laz'): 'FIS01-02_345920_8059500_25_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_27_seg.laz'): 'FIS01-02_345920_8059500_27_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_28_seg.laz'): 'FIS01-02_345920_8059500_28_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_29_seg.laz'): 'FIS01-02_345920_8059500_29_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_31_seg.laz'): 'FIS01-02_345920_8059500_31_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_32d_seg.laz'): 'FIS01-02_345920_8059500_32d_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_33_seg.laz'): 'FIS01-02_345920_8059500_33_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_34_seg.laz'): 'FIS01-02_345920_8059500_34_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_35_seg.laz'): 'FIS01-02_345920_8059500_35_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_00_seg.laz'): 'FIS01-02_345920_8059490_00_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_03_seg.laz'): 'FIS01-02_345920_8059490_03_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_04_seg.laz'): 'FIS01-02_345920_8059490_04_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_06_seg.laz'): 'FIS01-02_345920_8059490_06_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_07_seg.laz'): 'FIS01-02_345920_8059490_07_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_08_seg.laz'): 'FIS01-02_345920_8059490_08_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_09_seg.laz'): 'FIS01-02_345920_8059490_09_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_16_seg.laz'): 'FIS01-02_345920_8059490_16_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_19_seg.laz'): 'FIS01-02_345920_8059490_19_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_21_seg.laz'): 'FIS01-02_345920_8059490_21_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_22_seg.laz'): 'FIS01-02_345920_8059490_22_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_23_seg.laz'): 'FIS01-02_345920_8059490_23_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_24_seg.laz'): 'FIS01-02_345920_8059490_24_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_26_seg.laz'): 'FIS01-02_345920_8059490_26_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_32_seg.laz'): 'FIS01-02_345920_8059490_32_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_33_seg.laz'): 'FIS01-02_345920_8059490_33_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_35_seg.laz'): 'FIS01-02_345920_8059490_35_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_36d_seg.laz'): 'FIS01-02_345920_8059490_36d_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Lama_02_seg.laz'): 'FIS01-02_345910_8059490_02_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Lama_05_seg.laz'): 'FIS01-02_345910_8059490_05_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Lama_06_seg.laz'): 'FIS01-02_345910_8059490_06_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Lama_07_seg.laz'): 'FIS01-02_345910_8059490_07_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Lama_09_seg.laz'): 'FIS01-02_345910_8059490_09_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Lama_10_seg.laz'): 'FIS01-02_345910_8059490_10_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Lama_18_seg.laz'): 'FIS01-02_345910_8059490_18_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Lama_20_seg.laz'): 'FIS01-02_345910_8059490_20_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Lama_22_seg.laz'): 'FIS01-02_345910_8059490_22_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Lama_23_seg.laz'): 'FIS01-02_345910_8059490_23_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Lama_25_seg.laz'): 'FIS01-02_345910_8059490_25_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Lama_28_seg.laz'): 'FIS01-02_345910_8059490_28_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Mada_07_seg.laz'): 'FIS01-02_345910_8059500_07_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Mada_08_seg.laz'): 'FIS01-02_345910_8059500_08_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Mada_10_seg.laz'): 'FIS01-02_345910_8059500_10_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Mada_13_seg.laz'): 'FIS01-02_345910_8059500_13_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Mada_19_seg.laz'): 'FIS01-02_345910_8059500_19_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Mada_21_seg.laz'): 'FIS01-02_345910_8059500_21_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Mada_23_seg.laz'): 'FIS01-02_345910_8059500_23_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Mada_25_seg.laz'): 'FIS01-02_345910_8059500_25_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Mada_26_seg.laz'): 'FIS01-02_345910_8059500_26_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Mada_27_seg.laz'): 'FIS01-02_345910_8059500_27_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Naia_02_seg.laz'): 'FIS01-02_345920_8059510_02_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Naia_05_seg.laz'): 'FIS01-02_345920_8059510_05_seg.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Naia_06_seg.laz'): 'FIS01-02_345920_8059510_06_seg.laz',

## Suffix

I am using the `_seg` suffix, while I should use the `_cor` suffix

In [ ]:
pretty2old = {
    path: old_name.replace("_seg", "_cor") for path, old_name in pretty2old.items()
}
pretty2old

{Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Aata_02_seg.laz'): 'FIS01-02_345920_8059480_02_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Aata_05_seg.laz'): 'FIS01-02_345920_8059480_05_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Aata_08_seg.laz'): 'FIS01-02_345920_8059480_08_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Aata_14_seg.laz'): 'FIS01-02_345920_8059480_14_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Aata_15_seg.laz'): 'FIS01-02_345920_8059480_15_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Aata_16_seg.laz'): 'FIS01-02_345920_8059480_16_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Aata_17_seg.laz'): 'FIS01-02_345920_8059480_17_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Bako_12_seg.laz'): 'FIS01-02_345930_8059470_12_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Bako_15_seg.laz'): 'FIS01-02_345930_8059470_15_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Bako_25_seg.laz'): 'FIS01-02_345930_8059470_25_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Ceto_06_seg.laz'): 'FIS01-02_345940_8059470_06_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Ceto_14_seg.laz'): 'FIS01-02_345940_8059470_14_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Ceto_19_seg.laz'): 'FIS01-02_345940_8059470_19_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Daku_01_seg.laz'): 'FIS01-02_345940_8059480_01_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Daku_08_seg.laz'): 'FIS01-02_345940_8059480_08_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Daku_09_seg.laz'): 'FIS01-02_345940_8059480_09_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Daku_10_seg.laz'): 'FIS01-02_345940_8059480_10_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Daku_11_seg.laz'): 'FIS01-02_345940_8059480_11_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Daku_12_seg.laz'): 'FIS01-02_345940_8059480_12_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Daku_13_seg.laz'): 'FIS01-02_345940_8059480_13_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Daku_23_seg.laz'): 'FIS01-02_345940_8059480_23_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Daku_24_seg.laz'): 'FIS01-02_345940_8059480_24_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Daku_32p_seg.laz'): 'FIS01-02_345940_8059480_32p_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Daku_33_seg.laz'): 'FIS01-02_345940_8059480_33_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Daku_34_seg.laz'): 'FIS01-02_345940_8059480_34_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Ecto_00_seg.laz'): 'FIS01-02_345930_8059480_00_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Ecto_02_seg.laz'): 'FIS01-02_345930_8059480_02_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Ecto_03_seg.laz'): 'FIS01-02_345930_8059480_03_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Ecto_05_seg.laz'): 'FIS01-02_345930_8059480_05_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Ecto_06_seg.laz'): 'FIS01-02_345930_8059480_06_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Ecto_08_seg.laz'): 'FIS01-02_345930_8059480_08_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Ecto_09_seg.laz'): 'FIS01-02_345930_8059480_09_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Ecto_12_seg.laz'): 'FIS01-02_345930_8059480_12_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Ecto_13_seg.laz'): 'FIS01-02_345930_8059480_13_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Ecto_21_seg.laz'): 'FIS01-02_345930_8059480_21_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_00b_seg.laz'): 'FIS01-02_345930_8059490_00b_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_01_seg.laz'): 'FIS01-02_345930_8059490_01_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_02_seg.laz'): 'FIS01-02_345930_8059490_02_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_04_seg.laz'): 'FIS01-02_345930_8059490_04_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_05_seg.laz'): 'FIS01-02_345930_8059490_05_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_06_seg.laz'): 'FIS01-02_345930_8059490_06_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_10_seg.laz'): 'FIS01-02_345930_8059490_10_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_11_seg.laz'): 'FIS01-02_345930_8059490_11_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_12_seg.laz'): 'FIS01-02_345930_8059490_12_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_13_seg.laz'): 'FIS01-02_345930_8059490_13_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_14_seg.laz'): 'FIS01-02_345930_8059490_14_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_17_seg.laz'): 'FIS01-02_345930_8059490_17_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_21_seg.laz'): 'FIS01-02_345930_8059490_21_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_26_seg.laz'): 'FIS01-02_345930_8059490_26_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_29p_seg.laz'): 'FIS01-02_345930_8059490_29p_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_30p_seg.laz'): 'FIS01-02_345930_8059490_30p_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Faba_31_seg.laz'): 'FIS01-02_345930_8059490_31_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Gaga_02_seg.laz'): 'FIS01-02_345940_8059490_02_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Gaga_04_seg.laz'): 'FIS01-02_345940_8059490_04_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Gaga_09_seg.laz'): 'FIS01-02_345940_8059490_09_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Gaga_16_seg.laz'): 'FIS01-02_345940_8059490_16_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Gaga_31_seg.laz'): 'FIS01-02_345940_8059490_31_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Gaga_34_seg.laz'): 'FIS01-02_345940_8059490_34_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Hada_02_seg.laz'): 'FIS01-02_345940_8059500_02_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Hada_03_seg.laz'): 'FIS01-02_345940_8059500_03_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Hada_10_seg.laz'): 'FIS01-02_345940_8059500_10_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Hada_13_seg.laz'): 'FIS01-02_345940_8059500_13_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Hada_16_seg.laz'): 'FIS01-02_345940_8059500_16_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Hada_17_seg.laz'): 'FIS01-02_345940_8059500_17_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Hada_18_seg.laz'): 'FIS01-02_345940_8059500_18_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Hada_28_seg.laz'): 'FIS01-02_345940_8059500_28_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Hada_37_seg.laz'): 'FIS01-02_345940_8059500_37_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_00_seg.laz'): 'FIS01-02_345930_8059500_00_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_01_seg.laz'): 'FIS01-02_345930_8059500_01_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_03_seg.laz'): 'FIS01-02_345930_8059500_03_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_04_seg.laz'): 'FIS01-02_345930_8059500_04_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_06_seg.laz'): 'FIS01-02_345930_8059500_06_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_07_seg.laz'): 'FIS01-02_345930_8059500_07_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_08_seg.laz'): 'FIS01-02_345930_8059500_08_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_09_seg.laz'): 'FIS01-02_345930_8059500_09_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_13_seg.laz'): 'FIS01-02_345930_8059500_13_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_15_seg.laz'): 'FIS01-02_345930_8059500_15_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_16_seg.laz'): 'FIS01-02_345930_8059500_16_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_19_seg.laz'): 'FIS01-02_345930_8059500_19_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_21_seg.laz'): 'FIS01-02_345930_8059500_21_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_26b_seg.laz'): 'FIS01-02_345930_8059500_26b_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_35_seg.laz'): 'FIS01-02_345930_8059500_35_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Iago_41_seg.laz'): 'FIS01-02_345930_8059500_41_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_00_seg.laz'): 'FIS01-02_345920_8059500_00_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_02_seg.laz'): 'FIS01-02_345920_8059500_02_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_04_seg.laz'): 'FIS01-02_345920_8059500_04_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_05_seg.laz'): 'FIS01-02_345920_8059500_05_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_06_seg.laz'): 'FIS01-02_345920_8059500_06_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_20_seg.laz'): 'FIS01-02_345920_8059500_20_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_25_seg.laz'): 'FIS01-02_345920_8059500_25_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_27_seg.laz'): 'FIS01-02_345920_8059500_27_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_28_seg.laz'): 'FIS01-02_345920_8059500_28_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_29_seg.laz'): 'FIS01-02_345920_8059500_29_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_31_seg.laz'): 'FIS01-02_345920_8059500_31_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_32d_seg.laz'): 'FIS01-02_345920_8059500_32d_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_33_seg.laz'): 'FIS01-02_345920_8059500_33_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_34_seg.laz'): 'FIS01-02_345920_8059500_34_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Jaya_35_seg.laz'): 'FIS01-02_345920_8059500_35_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_00_seg.laz'): 'FIS01-02_345920_8059490_00_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_03_seg.laz'): 'FIS01-02_345920_8059490_03_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_04_seg.laz'): 'FIS01-02_345920_8059490_04_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_06_seg.laz'): 'FIS01-02_345920_8059490_06_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_07_seg.laz'): 'FIS01-02_345920_8059490_07_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_08_seg.laz'): 'FIS01-02_345920_8059490_08_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_09_seg.laz'): 'FIS01-02_345920_8059490_09_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_16_seg.laz'): 'FIS01-02_345920_8059490_16_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_19_seg.laz'): 'FIS01-02_345920_8059490_19_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_21_seg.laz'): 'FIS01-02_345920_8059490_21_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_22_seg.laz'): 'FIS01-02_345920_8059490_22_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_23_seg.laz'): 'FIS01-02_345920_8059490_23_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_24_seg.laz'): 'FIS01-02_345920_8059490_24_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_26_seg.laz'): 'FIS01-02_345920_8059490_26_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_32_seg.laz'): 'FIS01-02_345920_8059490_32_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_33_seg.laz'): 'FIS01-02_345920_8059490_33_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_35_seg.laz'): 'FIS01-02_345920_8059490_35_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Kali_36d_seg.laz'): 'FIS01-02_345920_8059490_36d_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Lama_02_seg.laz'): 'FIS01-02_345910_8059490_02_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Lama_05_seg.laz'): 'FIS01-02_345910_8059490_05_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Lama_06_seg.laz'): 'FIS01-02_345910_8059490_06_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Lama_07_seg.laz'): 'FIS01-02_345910_8059490_07_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Lama_09_seg.laz'): 'FIS01-02_345910_8059490_09_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Lama_10_seg.laz'): 'FIS01-02_345910_8059490_10_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Lama_18_seg.laz'): 'FIS01-02_345910_8059490_18_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Lama_20_seg.laz'): 'FIS01-02_345910_8059490_20_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Lama_22_seg.laz'): 'FIS01-02_345910_8059490_22_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Lama_23_seg.laz'): 'FIS01-02_345910_8059490_23_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Lama_25_seg.laz'): 'FIS01-02_345910_8059490_25_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Lama_28_seg.laz'): 'FIS01-02_345910_8059490_28_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Mada_07_seg.laz'): 'FIS01-02_345910_8059500_07_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Mada_08_seg.laz'): 'FIS01-02_345910_8059500_08_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Mada_10_seg.laz'): 'FIS01-02_345910_8059500_10_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Mada_13_seg.laz'): 'FIS01-02_345910_8059500_13_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Mada_19_seg.laz'): 'FIS01-02_345910_8059500_19_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Mada_21_seg.laz'): 'FIS01-02_345910_8059500_21_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Mada_23_seg.laz'): 'FIS01-02_345910_8059500_23_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Mada_25_seg.laz'): 'FIS01-02_345910_8059500_25_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Mada_26_seg.laz'): 'FIS01-02_345910_8059500_26_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Mada_27_seg.laz'): 'FIS01-02_345910_8059500_27_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Naia_02_seg.laz'): 'FIS01-02_345920_8059510_02_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Naia_05_seg.laz'): 'FIS01-02_345920_8059510_05_cor.laz',
 Path('c:/Users/smassaro/Documents/segmentation/Mount_fisher/Corrected_pretty_names/Naia_06_seg.laz'): 'FIS01-02_345920_8059510_06_cor.laz',

## Copy and rename

In [ ]:
import shutil
from pathlib import Path


def copy_rename_files(
    path_map: dict, # pretty path to old name
    target_folder: Path,
):
    for pretty_path, old_name in path_map.items():
        new_name = target_folder / old_name
        shutil.copy(pretty_path, new_name)
        print(f"{pretty_path.name} -> {new_name.name}")

In [ ]:
dir_cor.mkdir(exist_ok=True)

In [ ]:
len(pretty2old)

472

In [ ]:
copy_rename_files(pretty2old, dir_cor)

Aata_02_seg.laz -> FIS01-02_345920_8059480_02_cor.laz
Aata_05_seg.laz -> FIS01-02_345920_8059480_05_cor.laz
Aata_08_seg.laz -> FIS01-02_345920_8059480_08_cor.laz
Aata_14_seg.laz -> FIS01-02_345920_8059480_14_cor.laz
Aata_15_seg.laz -> FIS01-02_345920_8059480_15_cor.laz
Aata_16_seg.laz -> FIS01-02_345920_8059480_16_cor.laz
Aata_17_seg.laz -> FIS01-02_345920_8059480_17_cor.laz
Bako_12_seg.laz -> FIS01-02_345930_8059470_12_cor.laz
Bako_15_seg.laz -> FIS01-02_345930_8059470_15_cor.laz
Bako_25_seg.laz -> FIS01-02_345930_8059470_25_cor.laz
Ceto_06_seg.laz -> FIS01-02_345940_8059470_06_cor.laz
Ceto_14_seg.laz -> FIS01-02_345940_8059470_14_cor.laz
Ceto_19_seg.laz -> FIS01-02_345940_8059470_19_cor.laz
Daku_01_seg.laz -> FIS01-02_345940_8059480_01_cor.laz
Daku_08_seg.laz -> FIS01-02_345940_8059480_08_cor.laz
Daku_09_seg.laz -> FIS01-02_345940_8059480_09_cor.laz
Daku_10_seg.laz -> FIS01-02_345940_8059480_10_cor.laz
Daku_11_seg.laz -> FIS01-02_345940_8059480_11_cor.laz
Daku_12_seg.laz -> FIS01-02_345940_8059480_12_cor.laz
Daku_13_seg.laz -> FIS01-02_345940_8059480_13_cor.laz
Daku_23_seg.laz -> FIS01-02_345940_8059480_23_cor.laz
Daku_24_seg.laz -> FIS01-02_345940_8059480_24_cor.laz
Daku_32p_seg.laz -> FIS01-02_345940_8059480_32p_cor.laz
Daku_33_seg.laz -> FIS01-02_345940_8059480_33_cor.laz
Daku_34_seg.laz -> FIS01-02_345940_8059480_34_cor.laz
Ecto_00_seg.laz -> FIS01-02_345930_8059480_00_cor.laz
Ecto_02_seg.laz -> FIS01-02_345930_8059480_02_cor.laz
Ecto_03_seg.laz -> FIS01-02_345930_8059480_03_cor.laz
Ecto_05_seg.laz -> FIS01-02_345930_8059480_05_cor.laz
Ecto_06_seg.laz -> FIS01-02_345930_8059480_06_cor.laz
Ecto_08_seg.laz -> FIS01-02_345930_8059480_08_cor.laz
Ecto_09_seg.laz -> FIS01-02_345930_8059480_09_cor.laz
Ecto_12_seg.laz -> FIS01-02_345930_8059480_12_cor.laz
Ecto_13_seg.laz -> FIS01-02_345930_8059480_13_cor.laz
Ecto_21_seg.laz -> FIS01-02_345930_8059480_21_cor.laz
Faba_00b_seg.laz -> FIS01-02_345930_8059490_00b_cor.laz
Faba_01_seg.laz -> FIS01-02_345930_8059490_01_cor.laz
Faba_02_seg.laz -> FIS01-02_345930_8059490_02_cor.laz
Faba_04_seg.laz -> FIS01-02_345930_8059490_04_cor.laz
Faba_05_seg.laz -> FIS01-02_345930_8059490_05_cor.laz
Faba_06_seg.laz -> FIS01-02_345930_8059490_06_cor.laz
Faba_10_seg.laz -> FIS01-02_345930_8059490_10_cor.laz
Faba_11_seg.laz -> FIS01-02_345930_8059490_11_cor.laz
Faba_12_seg.laz -> FIS01-02_345930_8059490_12_cor.laz
Faba_13_seg.laz -> FIS01-02_345930_8059490_13_cor.laz
Faba_14_seg.laz -> FIS01-02_345930_8059490_14_cor.laz
Faba_17_seg.laz -> FIS01-02_345930_8059490_17_cor.laz
Faba_21_seg.laz -> FIS01-02_345930_8059490_21_cor.laz
Faba_26_seg.laz -> FIS01-02_345930_8059490_26_cor.laz
Faba_29p_seg.laz -> FIS01-02_345930_8059490_29p_cor.laz
Faba_30p_seg.laz -> FIS01-02_345930_8059490_30p_cor.laz
Faba_31_seg.laz -> FIS01-02_345930_8059490_31_cor.laz
Gaga_02_seg.laz -> FIS01-02_345940_8059490_02_cor.laz
Gaga_04_seg.laz -> FIS01-02_345940_8059490_04_cor.laz
Gaga_09_seg.laz -> FIS01-02_345940_8059490_09_cor.laz
Gaga_16_seg.laz -> FIS01-02_345940_8059490_16_cor.laz
Gaga_31_seg.laz -> FIS01-02_345940_8059490_31_cor.laz
Gaga_34_seg.laz -> FIS01-02_345940_8059490_34_cor.laz
Hada_02_seg.laz -> FIS01-02_345940_8059500_02_cor.laz
Hada_03_seg.laz -> FIS01-02_345940_8059500_03_cor.laz
Hada_10_seg.laz -> FIS01-02_345940_8059500_10_cor.laz
Hada_13_seg.laz -> FIS01-02_345940_8059500_13_cor.laz
Hada_16_seg.laz -> FIS01-02_345940_8059500_16_cor.laz
Hada_17_seg.laz -> FIS01-02_345940_8059500_17_cor.laz
Hada_18_seg.laz -> FIS01-02_345940_8059500_18_cor.laz
Hada_28_seg.laz -> FIS01-02_345940_8059500_28_cor.laz
Hada_37_seg.laz -> FIS01-02_345940_8059500_37_cor.laz
Iago_00_seg.laz -> FIS01-02_345930_8059500_00_cor.laz
Iago_01_seg.laz -> FIS01-02_345930_8059500_01_cor.laz
Iago_03_seg.laz -> FIS01-02_345930_8059500_03_cor.laz
Iago_04_seg.laz -> FIS01-02_345930_8059500_04_cor.laz
Iago_06_seg.laz -> FIS01-02_345930_8059500_06_cor.laz
Iago_07_seg.laz -> FIS01-02_345930_8059500_07_cor.laz
Iago_08_seg.laz -> FIS01-02_345930_8059500_08_cor.laz
Iago_09_seg.laz -> FIS01-02_345930_8059500_09_cor.laz
Iago_13_seg.laz -> FIS01-02_345930_8059500_13_cor.laz
Iago_15_seg.laz -> FIS01-02_345930_8059500_15_cor.laz
Iago_16_seg.laz -> FIS01-02_345930_8059500_16_cor.laz
Iago_19_seg.laz -> FIS01-02_345930_8059500_19_cor.laz
Iago_21_seg.laz -> FIS01-02_345930_8059500_21_cor.laz
Iago_26b_seg.laz -> FIS01-02_345930_8059500_26b_cor.laz
Iago_35_seg.laz -> FIS01-02_345930_8059500_35_cor.laz
Iago_41_seg.laz -> FIS01-02_345930_8059500_41_cor.laz
Jaya_00_seg.laz -> FIS01-02_345920_8059500_00_cor.laz
Jaya_02_seg.laz -> FIS01-02_345920_8059500_02_cor.laz
Jaya_04_seg.laz -> FIS01-02_345920_8059500_04_cor.laz
Jaya_05_seg.laz -> FIS01-02_345920_8059500_05_cor.laz
Jaya_06_seg.laz -> FIS01-02_345920_8059500_06_cor.laz
Jaya_20_seg.laz -> FIS01-02_345920_8059500_20_cor.laz
Jaya_25_seg.laz -> FIS01-02_345920_8059500_25_cor.laz
Jaya_27_seg.laz -> FIS01-02_345920_8059500_27_cor.laz
Jaya_28_seg.laz -> FIS01-02_345920_8059500_28_cor.laz
Jaya_29_seg.laz -> FIS01-02_345920_8059500_29_cor.laz
Jaya_31_seg.laz -> FIS01-02_345920_8059500_31_cor.laz
Jaya_32d_seg.laz -> FIS01-02_345920_8059500_32d_cor.laz
Jaya_33_seg.laz -> FIS01-02_345920_8059500_33_cor.laz
Jaya_34_seg.laz -> FIS01-02_345920_8059500_34_cor.laz
Jaya_35_seg.laz -> FIS01-02_345920_8059500_35_cor.laz
Kali_00_seg.laz -> FIS01-02_345920_8059490_00_cor.laz
Kali_03_seg.laz -> FIS01-02_345920_8059490_03_cor.laz
Kali_04_seg.laz -> FIS01-02_345920_8059490_04_cor.laz
Kali_06_seg.laz -> FIS01-02_345920_8059490_06_cor.laz
Kali_07_seg.laz -> FIS01-02_345920_8059490_07_cor.laz
Kali_08_seg.laz -> FIS01-02_345920_8059490_08_cor.laz
Kali_09_seg.laz -> FIS01-02_345920_8059490_09_cor.laz
Kali_16_seg.laz -> FIS01-02_345920_8059490_16_cor.laz
Kali_19_seg.laz -> FIS01-02_345920_8059490_19_cor.laz
Kali_21_seg.laz -> FIS01-02_345920_8059490_21_cor.laz
Kali_22_seg.laz -> FIS01-02_345920_8059490_22_cor.laz
Kali_23_seg.laz -> FIS01-02_345920_8059490_23_cor.laz
Kali_24_seg.laz -> FIS01-02_345920_8059490_24_cor.laz
Kali_26_seg.laz -> FIS01-02_345920_8059490_26_cor.laz
Kali_32_seg.laz -> FIS01-02_345920_8059490_32_cor.laz
Kali_33_seg.laz -> FIS01-02_345920_8059490_33_cor.laz
Kali_35_seg.laz -> FIS01-02_345920_8059490_35_cor.laz
Kali_36d_seg.laz -> FIS01-02_345920_8059490_36d_cor.laz
Lama_02_seg.laz -> FIS01-02_345910_8059490_02_cor.laz
Lama_05_seg.laz -> FIS01-02_345910_8059490_05_cor.laz
Lama_06_seg.laz -> FIS01-02_345910_8059490_06_cor.laz
Lama_07_seg.laz -> FIS01-02_345910_8059490_07_cor.laz
Lama_09_seg.laz -> FIS01-02_345910_8059490_09_cor.laz
Lama_10_seg.laz -> FIS01-02_345910_8059490_10_cor.laz
Lama_18_seg.laz -> FIS01-02_345910_8059490_18_cor.laz
Lama_20_seg.laz -> FIS01-02_345910_8059490_20_cor.laz
Lama_22_seg.laz -> FIS01-02_345910_8059490_22_cor.laz
Lama_23_seg.laz -> FIS01-02_345910_8059490_23_cor.laz
Lama_25_seg.laz -> FIS01-02_345910_8059490_25_cor.laz
Lama_28_seg.laz -> FIS01-02_345910_8059490_28_cor.laz
Mada_07_seg.laz -> FIS01-02_345910_8059500_07_cor.laz
Mada_08_seg.laz -> FIS01-02_345910_8059500_08_cor.laz
Mada_10_seg.laz -> FIS01-02_345910_8059500_10_cor.laz
Mada_13_seg.laz -> FIS01-02_345910_8059500_13_cor.laz
Mada_19_seg.laz -> FIS01-02_345910_8059500_19_cor.laz
Mada_21_seg.laz -> FIS01-02_345910_8059500_21_cor.laz
Mada_23_seg.laz -> FIS01-02_345910_8059500_23_cor.laz
Mada_25_seg.laz -> FIS01-02_345910_8059500_25_cor.laz
Mada_26_seg.laz -> FIS01-02_345910_8059500_26_cor.laz
Mada_27_seg.laz -> FIS01-02_345910_8059500_27_cor.laz
Naia_02_seg.laz -> FIS01-02_345920_8059510_02_cor.laz
Naia_05_seg.laz -> FIS01-02_345920_8059510_05_cor.laz
Naia_06_seg.laz -> FIS01-02_345920_8059510_06_cor.laz
Naia_10_seg.laz -> FIS01-02_345920_8059510_10_cor.laz
Naia_13_seg.laz -> FIS01-02_345920_8059510_13_cor.laz
Naia_16_seg.laz -> FIS01-02_345920_8059510_16_cor.laz
Naia_18_seg.laz -> FIS01-02_345920_8059510_18_cor.laz
Naia_20_seg.laz -> FIS01-02_345920_8059510_20_cor.laz
Naia_23_seg.laz -> FIS01-02_345920_8059510_23_cor.laz
Naia_25_seg.laz -> FIS01-02_345920_8059510_25_cor.laz
Naia_26_seg.laz -> FIS01-02_345920_8059510_26_cor.laz
Naia_27_seg.laz -> FIS01-02_345920_8059510_27_cor.laz
Obus_26_seg.laz -> FIS01-02_345910_8059510_26_cor.laz
Odax_06_seg.laz -> FIS01-02_345920_8059520_06_cor.laz
Odax_07_seg.laz -> FIS01-02_345920_8059520_07_cor.laz
Odax_08_seg.laz -> FIS01-02_345920_8059520_08_cor.laz
Odax_11_seg.laz -> FIS01-02_345920_8059520_11_cor.laz
Odax_13_seg.laz -> FIS01-02_345920_8059520_13_cor.laz
Odax_22_seg.laz -> FIS01-02_345920_8059520_22_cor.laz
Odax_23_seg.laz -> FIS01-02_345920_8059520_23_cor.laz
Odax_25_seg.laz -> FIS01-02_345920_8059520_25_cor.laz
Okea_00_seg.laz -> FIS01-02_345930_8059520_00_cor.laz
Okea_01_seg.laz -> FIS01-02_345930_8059520_01_cor.laz
Okea_04_seg.laz -> FIS01-02_345930_8059520_04_cor.laz
Okea_07_seg.laz -> FIS01-02_345930_8059520_07_cor.laz
Okea_09_seg.laz -> FIS01-02_345930_8059520_09_cor.laz
Okea_10_seg.laz -> FIS01-02_345930_8059520_10_cor.laz
Okea_11_seg.laz -> FIS01-02_345930_8059520_11_cor.laz
Okea_12_seg.laz -> FIS01-02_345930_8059520_12_cor.laz
Okea_13_seg.laz -> FIS01-02_345930_8059520_13_cor.laz
Okea_14_seg.laz -> FIS01-02_345930_8059520_14_cor.laz
Okea_17_seg.laz -> FIS01-02_345930_8059520_17_cor.laz
Okea_18_seg.laz -> FIS01-02_345930_8059520_18_cor.laz
Okea_19_seg.laz -> FIS01-02_345930_8059520_19_cor.laz
Okea_22_seg.laz -> FIS01-02_345930_8059520_22_cor.laz
Okea_23_seg.laz -> FIS01-02_345930_8059520_23_cor.laz
Okea_24b_seg.laz -> FIS01-02_345930_8059520_24b_cor.laz
Omus_01_seg.laz -> FIS01-02_345930_8059530_01_cor.laz
Omus_02_seg.laz -> FIS01-02_345930_8059530_02_cor.laz
Omus_05_seg.laz -> FIS01-02_345930_8059530_05_cor.laz
Omus_07_seg.laz -> FIS01-02_345930_8059530_07_cor.laz
Omus_08_seg.laz -> FIS01-02_345930_8059530_08_cor.laz
Omus_10_seg.laz -> FIS01-02_345930_8059530_10_cor.laz
Omus_11_seg.laz -> FIS01-02_345930_8059530_11_cor.laz
Omus_12_seg.laz -> FIS01-02_345930_8059530_12_cor.laz
Omus_14_seg.laz -> FIS01-02_345930_8059530_14_cor.laz
Omus_15_seg.laz -> FIS01-02_345930_8059530_15_cor.laz
Omus_17_seg.laz -> FIS01-02_345930_8059530_17_cor.laz
Omus_18_seg.laz -> FIS01-02_345930_8059530_18_cor.laz
Omus_20_seg.laz -> FIS01-02_345930_8059530_20_cor.laz
Owra_00_seg.laz -> FIS01-02_345940_8059530_00_cor.laz
Owra_01_seg.laz -> FIS01-02_345940_8059530_01_cor.laz
Owra_04_seg.laz -> FIS01-02_345940_8059530_04_cor.laz
Owra_06_seg.laz -> FIS01-02_345940_8059530_06_cor.laz
Owra_08_seg.laz -> FIS01-02_345940_8059530_08_cor.laz
Owra_10_seg.laz -> FIS01-02_345940_8059530_10_cor.laz
Owra_12_seg.laz -> FIS01-02_345940_8059530_12_cor.laz
Owra_15_seg.laz -> FIS01-02_345940_8059530_15_cor.laz
Owra_16_seg.laz -> FIS01-02_345940_8059530_16_cor.laz
Owra_17_seg.laz -> FIS01-02_345940_8059530_17_cor.laz
Oxya_01_seg.laz -> FIS01-02_345940_8059520_01_cor.laz
Oxya_03_seg.laz -> FIS01-02_345940_8059520_03_cor.laz
Oxya_04_seg.laz -> FIS01-02_345940_8059520_04_cor.laz
Oxya_07_seg.laz -> FIS01-02_345940_8059520_07_cor.laz
Oxya_08_seg.laz -> FIS01-02_345940_8059520_08_cor.laz
Oxya_09_seg.laz -> FIS01-02_345940_8059520_09_cor.laz
Oxya_10_seg.laz -> FIS01-02_345940_8059520_10_cor.laz
Oxya_16_seg.laz -> FIS01-02_345940_8059520_16_cor.laz
Oxya_17_seg.laz -> FIS01-02_345940_8059520_17_cor.laz
Oxya_18_seg.laz -> FIS01-02_345940_8059520_18_cor.laz
Oxya_20_seg.laz -> FIS01-02_345940_8059520_20_cor.laz
Paha_00_seg.laz -> FIS01-02_345940_8059510_00_cor.laz
Paha_01_seg.laz -> FIS01-02_345940_8059510_01_cor.laz
Paha_02_seg.laz -> FIS01-02_345940_8059510_02_cor.laz
Paha_03_seg.laz -> FIS01-02_345940_8059510_03_cor.laz
Paha_04_seg.laz -> FIS01-02_345940_8059510_04_cor.laz
Paha_05_seg.laz -> FIS01-02_345940_8059510_05_cor.laz
Paha_06_seg.laz -> FIS01-02_345940_8059510_06_cor.laz
Paha_07_seg.laz -> FIS01-02_345940_8059510_07_cor.laz
Paha_08_seg.laz -> FIS01-02_345940_8059510_08_cor.laz
Paha_10_seg.laz -> FIS01-02_345940_8059510_10_cor.laz
Paha_11_seg.laz -> FIS01-02_345940_8059510_11_cor.laz
Paha_12_seg.laz -> FIS01-02_345940_8059510_12_cor.laz
Paha_13_seg.laz -> FIS01-02_345940_8059510_13_cor.laz
Paha_15_seg.laz -> FIS01-02_345940_8059510_15_cor.laz
Paha_16_seg.laz -> FIS01-02_345940_8059510_16_cor.laz
Paha_17_seg.laz -> FIS01-02_345940_8059510_17_cor.laz
Paha_18_seg.laz -> FIS01-02_345940_8059510_18_cor.laz
Paha_19_seg.laz -> FIS01-02_345940_8059510_19_cor.laz
Paha_20_seg.laz -> FIS01-02_345940_8059510_20_cor.laz
Paha_25_seg.laz -> FIS01-02_345940_8059510_25_cor.laz
Paha_26_seg.laz -> FIS01-02_345940_8059510_26_cor.laz
Paha_28p_seg.laz -> FIS01-02_345940_8059510_28p_cor.laz
Psoa_00_seg.laz -> FIS01-02_345930_8059510_00_cor.laz
Psoa_01_seg.laz -> FIS01-02_345930_8059510_01_cor.laz
Psoa_02_seg.laz -> FIS01-02_345930_8059510_02_cor.laz
Psoa_04_seg.laz -> FIS01-02_345930_8059510_04_cor.laz
Psoa_06_seg.laz -> FIS01-02_345930_8059510_06_cor.laz
Psoa_11_seg.laz -> FIS01-02_345930_8059510_11_cor.laz
Psoa_14_seg.laz -> FIS01-02_345930_8059510_14_cor.laz
Psoa_15_seg.laz -> FIS01-02_345930_8059510_15_cor.laz
Psoa_20_seg.laz -> FIS01-02_345930_8059510_20_cor.laz
Ptyx_00_seg.laz -> FIS01-02_345950_8059510_00_cor.laz
Ptyx_01_seg.laz -> FIS01-02_345950_8059510_01_cor.laz
Ptyx_02_seg.laz -> FIS01-02_345950_8059510_02_cor.laz
Ptyx_03_seg.laz -> FIS01-02_345950_8059510_03_cor.laz
Ptyx_04_seg.laz -> FIS01-02_345950_8059510_04_cor.laz
Ptyx_06_seg.laz -> FIS01-02_345950_8059510_06_cor.laz
Ptyx_08_seg.laz -> FIS01-02_345950_8059510_08_cor.laz
Ptyx_09_seg.laz -> FIS01-02_345950_8059510_09_cor.laz
Ptyx_13_seg.laz -> FIS01-02_345950_8059510_13_cor.laz
Ptyx_14_seg.laz -> FIS01-02_345950_8059510_14_cor.laz
Ptyx_17_seg.laz -> FIS01-02_345950_8059510_17_cor.laz
Ptyx_20_seg.laz -> FIS01-02_345950_8059510_20_cor.laz
Ptyx_22_seg.laz -> FIS01-02_345950_8059510_22_cor.laz
Ptyx_23p_seg.laz -> FIS01-02_345950_8059510_23p_cor.laz
Ptyx_24p_seg.laz -> FIS01-02_345950_8059510_24p_cor.laz
Raja_05_seg.laz -> FIS01-02_345950_8059530_05_cor.laz
Raja_06_seg.laz -> FIS01-02_345950_8059530_06_cor.laz
Raja_07_seg.laz -> FIS01-02_345950_8059530_07_cor.laz
Raja_08_seg.laz -> FIS01-02_345950_8059530_08_cor.laz
Raja_15_seg.laz -> FIS01-02_345950_8059530_15_cor.laz
Raja_16_seg.laz -> FIS01-02_345950_8059530_16_cor.laz
Raja_17_seg.laz -> FIS01-02_345950_8059530_17_cor.laz
Raja_21_seg.laz -> FIS01-02_345950_8059530_21_cor.laz
Saba_00_seg.laz -> FIS01-02_345950_8059520_00_cor.laz
Saba_04_seg.laz -> FIS01-02_345950_8059520_04_cor.laz
Saba_05_seg.laz -> FIS01-02_345950_8059520_05_cor.laz
Saba_06_seg.laz -> FIS01-02_345950_8059520_06_cor.laz
Saba_09_seg.laz -> FIS01-02_345950_8059520_09_cor.laz
Saba_10_seg.laz -> FIS01-02_345950_8059520_10_cor.laz
Saba_13_seg.laz -> FIS01-02_345950_8059520_13_cor.laz
Saba_15_seg.laz -> FIS01-02_345950_8059520_15_cor.laz
Saba_21_seg.laz -> FIS01-02_345950_8059520_21_cor.laz
Spio_03_seg.laz -> FIS01-02_345960_8059520_03_cor.laz
Spio_04_seg.laz -> FIS01-02_345960_8059520_04_cor.laz
Spio_08d_seg.laz -> FIS01-02_345960_8059520_08d_cor.laz
Spio_09_seg.laz -> FIS01-02_345960_8059520_09_cor.laz
Spio_13_seg.laz -> FIS01-02_345960_8059520_13_cor.laz
Spio_26_seg.laz -> FIS01-02_345960_8059520_26_cor.laz
Spio_27_seg.laz -> FIS01-02_345960_8059520_27_cor.laz
Spio_29p_seg.laz -> FIS01-02_345960_8059520_29p_cor.laz
Spio_30_seg.laz -> FIS01-02_345960_8059520_30_cor.laz
Spio_31p_seg.laz -> FIS01-02_345960_8059520_31p_cor.laz
Taia_03_seg.laz -> FIS01-02_345960_8059530_03_cor.laz
Taia_04_seg.laz -> FIS01-02_345960_8059530_04_cor.laz
Taia_06_seg.laz -> FIS01-02_345960_8059530_06_cor.laz
Taia_09_seg.laz -> FIS01-02_345960_8059530_09_cor.laz
Taia_19_seg.laz -> FIS01-02_345960_8059530_19_cor.laz
Taia_27_seg.laz -> FIS01-02_345960_8059530_27_cor.laz
Taia_36_seg.laz -> FIS01-02_345960_8059530_36_cor.laz
Taia_37_seg.laz -> FIS01-02_345960_8059530_37_cor.laz
Taia_38_seg.laz -> FIS01-02_345960_8059530_38_cor.laz
Taia_39_seg.laz -> FIS01-02_345960_8059530_39_cor.laz
Thor_02_seg.laz -> FIS01-02_345970_8059530_02_cor.laz
Thor_08_seg.laz -> FIS01-02_345970_8059530_08_cor.laz
Thor_12_seg.laz -> FIS01-02_345970_8059530_12_cor.laz
Thor_40_seg.laz -> FIS01-02_345970_8059530_40_cor.laz
Thor_41_seg.laz -> FIS01-02_345970_8059530_41_cor.laz
Uaru_00_seg.laz -> FIS01-02_345960_8059510_00_cor.laz
Uaru_03_seg.laz -> FIS01-02_345960_8059510_03_cor.laz
Uaru_04_seg.laz -> FIS01-02_345960_8059510_04_cor.laz
Uaru_06_seg.laz -> FIS01-02_345960_8059510_06_cor.laz
Uaru_20_seg.laz -> FIS01-02_345960_8059510_20_cor.laz
Uaru_21p_seg.laz -> FIS01-02_345960_8059510_21p_cor.laz
Ubis_01_seg.laz -> FIS01-02_345960_8059500_01_cor.laz
Ubis_02_seg.laz -> FIS01-02_345960_8059500_02_cor.laz
Ucla_01_seg.laz -> FIS01-02_345950_8059500_01_cor.laz
Ucla_03_seg.laz -> FIS01-02_345950_8059500_03_cor.laz
Ucla_11_seg.laz -> FIS01-02_345950_8059500_11_cor.laz
Ucla_18_seg.laz -> FIS01-02_345950_8059500_18_cor.laz
Ucla_26_seg.laz -> FIS01-02_345950_8059500_26_cor.laz
Ucla_28_seg.laz -> FIS01-02_345950_8059500_28_cor.laz
Ucla_33_seg.laz -> FIS01-02_345950_8059500_33_cor.laz
Ucla_35_seg.laz -> FIS01-02_345950_8059500_35_cor.laz
Ucla_36p_seg.laz -> FIS01-02_345950_8059500_36p_cor.laz
Ucla_37_seg.laz -> FIS01-02_345950_8059500_37_cor.laz
Ucla_38p_seg.laz -> FIS01-02_345950_8059500_38p_cor.laz
Ugni_00_seg.laz -> FIS01-02_345950_8059490_00_cor.laz
Ugni_05_seg.laz -> FIS01-02_345950_8059490_05_cor.laz
Ugni_18_seg.laz -> FIS01-02_345950_8059490_18_cor.laz
Ugni_28_seg.laz -> FIS01-02_345950_8059490_28_cor.laz
Ulva_01_seg.laz -> FIS01-02_345980_8059550_01_cor.laz
Ulva_22_seg.laz -> FIS01-02_345980_8059550_22_cor.laz
Unio_00_seg.laz -> FIS01-02_345960_8059560_00_cor.laz
Unio_06_seg.laz -> FIS01-02_345960_8059560_06_cor.laz
Unio_17_seg.laz -> FIS01-02_345960_8059560_17_cor.laz
Unio_18_seg.laz -> FIS01-02_345960_8059560_18_cor.laz
Unio_30_seg.laz -> FIS01-02_345960_8059560_30_cor.laz
Urva_00_seg.laz -> FIS01-02_345960_8059550_00_cor.laz
Urva_01_seg.laz -> FIS01-02_345960_8059550_01_cor.laz
Urva_02_seg.laz -> FIS01-02_345960_8059550_02_cor.laz
Urva_05_seg.laz -> FIS01-02_345960_8059550_05_cor.laz
Urva_06_seg.laz -> FIS01-02_345960_8059550_06_cor.laz
Urva_07_seg.laz -> FIS01-02_345960_8059550_07_cor.laz
Urva_08_seg.laz -> FIS01-02_345960_8059550_08_cor.laz
Urva_09_seg.laz -> FIS01-02_345960_8059550_09_cor.laz
Urva_10_seg.laz -> FIS01-02_345960_8059550_10_cor.laz
Urva_12_seg.laz -> FIS01-02_345960_8059550_12_cor.laz
Urva_14_seg.laz -> FIS01-02_345960_8059550_14_cor.laz
Urva_15_seg.laz -> FIS01-02_345960_8059550_15_cor.laz
Urva_18_seg.laz -> FIS01-02_345960_8059550_18_cor.laz
Urva_19_seg.laz -> FIS01-02_345960_8059550_19_cor.laz
Urva_21_seg.laz -> FIS01-02_345960_8059550_21_cor.laz
Urva_22_seg.laz -> FIS01-02_345960_8059550_22_cor.laz
Urva_26_seg.laz -> FIS01-02_345960_8059550_26_cor.laz
Urva_27_seg.laz -> FIS01-02_345960_8059550_27_cor.laz
Urva_36_seg.laz -> FIS01-02_345960_8059550_36_cor.laz
Urva_37_seg.laz -> FIS01-02_345960_8059550_37_cor.laz
Urva_40_seg.laz -> FIS01-02_345960_8059550_40_cor.laz
Uvik_03_seg.laz -> FIS01-02_345970_8059550_03_cor.laz
Uvik_07_seg.laz -> FIS01-02_345970_8059550_07_cor.laz
Uvik_15_seg.laz -> FIS01-02_345970_8059550_15_cor.laz
Uvik_27_seg.laz -> FIS01-02_345970_8059550_27_cor.laz
Uvik_28_seg.laz -> FIS01-02_345970_8059550_28_cor.laz
Uvik_34_seg.laz -> FIS01-02_345970_8059550_34_cor.laz
Uvik_51_seg.laz -> FIS01-02_345970_8059550_51_cor.laz
Vaga_00_seg.laz -> FIS01-02_345970_8059540_00_cor.laz
Vaga_01_seg.laz -> FIS01-02_345970_8059540_01_cor.laz
Vaga_03_seg.laz -> FIS01-02_345970_8059540_03_cor.laz
Vaga_07_seg.laz -> FIS01-02_345970_8059540_07_cor.laz
Vaga_26_seg.laz -> FIS01-02_345970_8059540_26_cor.laz
Vaga_28_seg.laz -> FIS01-02_345970_8059540_28_cor.laz
Vaga_29_seg.laz -> FIS01-02_345970_8059540_29_cor.laz
Vini_00_seg.laz -> FIS01-02_345960_8059540_00_cor.laz
Vini_01_seg.laz -> FIS01-02_345960_8059540_01_cor.laz
Vini_03_seg.laz -> FIS01-02_345960_8059540_03_cor.laz
Vini_04_seg.laz -> FIS01-02_345960_8059540_04_cor.laz
Vini_05_seg.laz -> FIS01-02_345960_8059540_05_cor.laz
Vini_07_seg.laz -> FIS01-02_345960_8059540_07_cor.laz
Vini_10_seg.laz -> FIS01-02_345960_8059540_10_cor.laz

## Updated crowns vector

Need to make sure that the crowns vector file contains two columsn with this format

```
GIS_ID	ID_number
WHY01-01_322330_8191020_18	322330_8191020_18
WHY01-01_322330_8191020_31	322330_8191020_31
WHY01-01_322330_8191020_35d	322330_8191020_35d
WHY01-01_322340_8190980_17	322340_8190980_17
```

I need to **overwrite** because of the new trees

In [ ]:
crowns['GIS_ID'] = crowns['pretty_name'].map(get_old_name)
crowns['ID_number'] = crowns['GIS_ID'].str.replace(f"{prefix}_", "")

In [ ]:
crowns.head(5)

,GIS_ID,ID_number,area,area.1,cell_id,grid_x,grid_y,grid_x_norm,grid_y_norm,hilbert_dist,suffix,pretty_name,segmented,notes,is_dead,is_removed,is_new,geometry
0,FIS01-02_345910_8059490_02,345910_8059490_02,3.651367,3.651367,345910_8059490,345910.0,8059490.0,0.0,20.0,944.0,02,Lama_02,True,None,False,NaN,NaN,"POLYGON ((345910.853 8059491.292, 345910.858 8..."
1,FIS01-02_345910_8059490_05,345910_8059490_05,16.017580,16.017580,345910_8059490,345910.0,8059490.0,0.0,20.0,944.0,05,Lama_05,True,None,False,NaN,NaN,"POLYGON ((345908.036 8059493.668, 345908.036 8..."
2,FIS01-02_345910_8059490_06,345910_8059490_06,4.727412,4.727412,345910_8059490,345910.0,8059490.0,0.0,20.0,944.0,06,Lama_06,True,None,False,NaN,NaN,"POLYGON ((345912.998 8059497.032, 345913.008 8..."
3,FIS01-02_345910_8059490_07,345910_8059490_07,10.067097,10.067097,345910_8059490,345910.0,8059490.0,0.0,20.0,944.0,07,Lama_07,True,None,False,NaN,NaN,"POLYGON ((345913.142 8059489.798, 345913.19 80..."
4,FIS01-02_345910_8059490_09,345910_8059490_09,3.543199,3.543199,345910_8059490,345910.0,8059490.0,0.0,20.0,944.0,09,Lama_09,True,None,False,NaN,NaN,"POLYGON ((345914.558 8059495.864, 345914.568 8..."

In [ ]:
crowns.to_file(crowns_path, driver="GPKG", layer = crowns_path.stem)